name: Build and deploy Application
on:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME_SERVICE1: jb-Service1-app
  AZURE_WEBAPP_NAME_SERVICE2: jb-Service2-app
  AZURE_WEBAPP_NAME_MERGE: jb-MergeService-app
  AZURE_WEBAPP_NAME_FRONT: jb-FrontEnd-app
  AZURE_WEBAPP_PACKAGE_PATH: /publish
  AZURE_WEBAPP_PUBLISH_PROFILE_SERVICE1: ${{ secrets.jb_Service1_app_615a }}
  AZURE_WEBAPP_PUBLISH_PROFILE_SERVICE2: ${{ secrets.jb_Service2_app_6bd0 }}
  AZURE_WEBAPP_PUBLISH_PROFILE_MERGE: ${{ secrets.jb_MergeService_app_3827 }}
  AZURE_WEBAPP_PUBLISH_PROFILE_FRONT: ${{ secrets.jb_FrontEnd_app_5f0c }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.x
  WORKING_DIRECTORY_SERVICE1: ./code/Service1
  WORKING_DIRECTORY_SERVICE2: ./code/Service2
  WORKING_DIRECTORY_MERGE: ./code/MergeService
  WORKING_DIRECTORY_FRONT: ./code/FrontEnd
  TEST_DIRECTORY: ./code/Project2/Tests


jobs:

  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo 'Hello Test'
        #run: dotnet test "${{ env.TEST_DIRECTORY }}" 
  build-and-deploy-service1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY_SERVICE1 }}/"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY_SERVICE1 }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY_SERVICE1 }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY_SERVICE1 }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_SERVICE1 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE_SERVICE1 }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  build-and-deploy-service2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY_SERVICE2 }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY_SERVICE2 }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY_SERVICE2 }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY_SERVICE2 }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_SERVICE2 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE_SERVICE2 }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  build-and-deploy-merge:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY_MERGE }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY_MERGE }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY_MERGE }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY_MERGE }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_MERGE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE_MERGE }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  build-and-deploy-front:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY_FRONT }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY_FRONT }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY_FRONT }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY_FRONT }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_FRONT }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE_FRONT }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}